// Renders probe results as Markdown: a capability matrix, per-model details, and quality files.

import type { Coverage, Distribution, OverheadFit, RoundTrip, SemanticsReport } from './analysis.mts';
import type { ApiFailure, Usage } from './api.mts';
import type { Candidate } from './candidates.mts';

export interface CheckResult {
  pass: boolean;
  detail: string;
}

export interface ModelResult {
  candidate: Candidate;
  available: boolean;
  resolvedModel: string | null;
  error: ApiFailure | null;
  skippedForBudget: boolean;
  checks: {
    streamedLogprobs: CheckResult;
    reasoningZero: CheckResult;
    samplingControls: CheckResult;
    roundTrip: CheckResult;
    retirement: CheckResult;
  };
  quality: { file: string | null; replies: number; failures: number };
  info: {
    topLogprobsUsed: number | null;
    streamedAlternatives: Distribution | null;
    finalAlternatives: Distribution | null;
    chosenOutside: { total: number; outside: number; rate: number | null } | null;
    tokensPerEvent: Record<string, number>;
    textMatchesDone: boolean | null;
    /** usage.output_tokens − reasoning − visible tokens, per fully covered call: tokens OpenAI counts but never returns. */
    hiddenOutputTokens: Distribution | null;
    coverage: Coverage | null;
    /** Streams whose final logprob list was empty or differed in length from the streamed entries. */
    finalLogprobs: { streams: number; empty: number; countMismatch: number };
    roundTrip: RoundTrip | null;
    semantics: SemanticsReport | null;
    timing: { createdMs: Distribution | null; firstTextMs: Distribution | null; createdToFirstTextMs: Distribution | null };
    cache: { first: Usage | null; second: Usage | null } | null;
    incomplete: { status: string | null; reason: string | null } | null;
    overhead: OverheadFit | null;
    unicodeText: string | null;
  };
  calls: number;
  costUsd: number;
  verdict: 'pass' | 'fail' | 'unavailable';
}

export interface RunMeta {
  date: string;
  startedAt: string;
  node: string;
  openaiSdk: string;
  gptTokenizer: string;
  priceTableDate: string;
  priceSource: string;
  totalCostUsd: number;
  maxUsd: number;
}

const yesNo = (check: CheckResult) => (check.pass ? 'pass' : '**FAIL**');
const fmtUsd = (usd: number) => `$${usd.toFixed(4)}`;
const fmtDist = (d: Distribution | null, unit = '') =>
  d ? `min ${round(d.min)}${unit} · median ${round(d.median)}${unit} · max ${round(d.max)}${unit} (n=${d.count})` : 'n/a';
const round = (n: number) => (Math.abs(n) >= 100 ? Math.round(n) : Math.round(n * 100) / 100);
const pct = (rate: number | null) => (rate === null ? 'n/a' : `${(rate * 100).toFixed(1)}%`);

function semanticsSentence(s: SemanticsReport | null): string {
  if (!s) return 'Not measured.';
  switch (s.semantics) {
    case 'raw':
      return 'The reported logprobs did not change with temperature, so they are the model’s raw scores. At the app’s settings (temperature 1, top_p 1) they equal the chances of each pick.';
    case 'temperature-scaled':
      return 'The reported logprobs changed by about 1/T with temperature, so they were computed after temperature scaling.';
    case 'inconclusive':
      return 'Inconclusive: the runs fit neither hypothesis within tolerance. Keep the copy free of any claim about it.';
  }
}

export function renderReport(meta: RunMeta, results: readonly ModelResult[]): string {
  const lines: string[] = [];
  const recommended = results.find((r) => r.verdict === 'pass');
  lines.push(`# Capability probe: ${meta.date}`, '');
  lines.push(
    `Run started ${meta.startedAt} · Node ${meta.node} · openai ${meta.openaiSdk} · gpt-tokenizer ${meta.gptTokenizer} (o200k_base)`,
    `Estimated cost of this run: **${fmtUsd(meta.totalCostUsd)}** (budget guard ${fmtUsd(meta.maxUsd)}), calculated from reported usage × the price table dated ${meta.priceTableDate} (${meta.priceSource}).`,
    '',
    'Generated by `npm run probe`. The rule (docs/PLAN.md, decision D3): pick the cheapest candidate that passes every automatic check, then confirm its reply quality by reading its quality file.',
    '',
  );
  lines.push('## Summary', '');
  lines.push(
    '| Model (cost order) | $/1M in · out | Streamed top-20 logprobs | reasoning_tokens = 0 | temperature & top_p | Tokenizer round-trip | Retirement | Verdict |',
    '|---|---|---|---|---|---|---|---|',
  );
  for (const r of results) {
    const c = r.checks;
    const price = `${r.candidate.price.input} · ${r.candidate.price.output}`;
    if (r.verdict === 'unavailable') {
      lines.push(`| \`${r.candidate.id}\` | ${price} | unavailable | | | | | unavailable |`);
      continue;
    }
    lines.push(
      `| \`${r.candidate.id}\` | ${price} | ${yesNo(c.streamedLogprobs)} | ${yesNo(c.reasoningZero)} | ${yesNo(c.samplingControls)} | ${yesNo(c.roundTrip)} | ${yesNo(c.retirement)} | ${r.verdict === 'pass' ? '**pass**' : 'fail'} |`,
    );
  }
  lines.push('');
  lines.push(
    recommended
      ? `**Cheapest candidate that passed every automatic check: \`${recommended.candidate.id}\`.** Before adopting it, read its replies in ${recommended.quality.file ? `\`${recommended.quality.file}\`` : 'its quality file'}.`
      : '**No candidate passed every automatic check.** See the details below.',
    '',
  );

  for (const r of results) {
    lines.push(`## \`${r.candidate.id}\``, '');
    lines.push(`- **Notes:** ${r.candidate.notes}`);
    if (r.verdict === 'unavailable') {
      lines.push(`- **Unavailable:** ${r.error ? `${r.error.status ?? ''} ${r.error.code ?? ''} ${r.error.message}`.trim() : 'no response'}`, '');
      continue;
    }
    lines.push(`- **Resolved snapshot:** \`${r.resolvedModel ?? 'unknown'}\` · **calls:** ${r.calls} · **cost:** ${fmtUsd(r.costUsd)}${r.skippedForBudget ? ' · **stopped early by the budget guard**' : ''}`);
    for (const [name, check] of Object.entries(r.checks)) lines.push(`- **${name}:** ${check.pass ? 'pass' : 'FAIL'}. ${check.detail}`);
    const i = r.info;
    lines.push(
      `- **Logprobs requested:** top_logprobs=${i.topLogprobsUsed ?? 'n/a'} · alternatives per streamed token: ${fmtDist(i.streamedAlternatives)} · per final token: ${fmtDist(i.finalAlternatives)}`,
      `- **Chosen token outside its returned alternatives:** ${i.chosenOutside ? `${i.chosenOutside.outside} of ${i.chosenOutside.total} (${pct(i.chosenOutside.rate)})` : 'n/a'}`,
      `- **Tokens per text delta event:** ${Object.entries(i.tokensPerEvent).map(([k, v]) => `${k} token(s) × ${v}`).join(', ') || 'n/a'}`,
      `- **Integrity:** deltas joined equal the done text: ${i.textMatchesDone ?? 'n/a'}`,
      `- **Hidden output tokens** (usage.output_tokens minus visible tokens, fully covered calls): ${fmtDist(i.hiddenOutputTokens)}`,
      `- **Logprob coverage:** ${i.coverage ? `${i.coverage.deltasWithoutLogprobs} of ${i.coverage.deltas} text deltas (${i.coverage.charsWithoutLogprobs} of ${i.coverage.chars} characters) arrived without logprobs${i.coverage.examples.length > 0 ? `, e.g. ${i.coverage.examples.map((e) => JSON.stringify(e)).join(', ')}` : ''}` : 'n/a'} · final logprob list empty in ${i.finalLogprobs.empty} of ${i.finalLogprobs.streams} streams, length differs from streamed entries in ${i.finalLogprobs.countMismatch}`,
      `- **Tokenizer round-trip:** ${i.roundTrip ? `${i.roundTrip.single} of ${i.roundTrip.checkable} checkable tokens are one o200k_base token (${pct(i.roundTrip.rate)}); ${i.roundTrip.partialBytes} tokens held partial UTF-8 characters` : 'n/a'}${i.roundTrip && i.roundTrip.mismatches.length > 0 ? `. Examples that were not: ${i.roundTrip.mismatches.slice(0, 8).map((m) => `${JSON.stringify(m.token)}→${m.localPieces}`).join(', ')}` : ''}`,
      `- **Logprob semantics (output position 1):** ${semanticsSentence(i.semantics)}${i.semantics ? ` Noise between identical runs: ${i.semantics.noise === null ? 'n/a' : round(i.semantics.noise)}; tolerance ${round(i.semantics.tolerance)}.` : ''}`,
    );
    if (i.semantics) {
      for (const run of i.semantics.runs) {
        const topPNote =
          run.topP < 1 && i.finalAlternatives && run.alternatives < i.finalAlternatives.median
            ? ` → top_p=${run.topP} shortened the returned list (shared values differ by at most ${run.maxAbsDiff === null ? 'n/a' : round(run.maxAbsDiff)})`
            : '';
        lines.push(
          `  - ${run.label}: ${run.alternatives} alternatives, ${run.common} shared with T=1 · max |Δ| ${run.maxAbsDiff === null ? 'n/a' : round(run.maxAbsDiff)} · gap ratio ${run.gapRatio === null ? 'n/a' : round(run.gapRatio)} (1/T would be ${run.expectedIfScaled === null ? 'n/a' : round(run.expectedIfScaled)})${topPNote}`,
        );
      }
    }
    lines.push(
      `- **Timing (measured by this script, includes network):** response.created at ${fmtDist(i.timing.createdMs, ' ms')}; first text at ${fmtDist(i.timing.firstTextMs, ' ms')}; created → first text ${fmtDist(i.timing.createdToFirstTextMs, ' ms')}`,
      `- **Prompt caching (same ~1.2k-token instructions twice):** ${i.cache ? `first call cached ${i.cache.first?.input_tokens_details.cached_tokens ?? 'n/a'} / wrote ${i.cache.first?.input_tokens_details.cache_write_tokens ?? 'n/a'} of ${i.cache.first?.input_tokens ?? 'n/a'}; second call cached ${i.cache.second?.input_tokens_details.cached_tokens ?? 'n/a'} / wrote ${i.cache.second?.input_tokens_details.cache_write_tokens ?? 'n/a'} of ${i.cache.second?.input_tokens ?? 'n/a'}` : 'n/a'}`,
      `- **Tiny output limit (16 tokens):** status ${i.incomplete?.status ?? 'n/a'}, reason ${i.incomplete?.reason ?? 'n/a'}`,
      `- **Input-count calibration:** ${i.overhead ? `OpenAI's count ≈ local o200k_base count + ${round(i.overhead.perRequest)} per request + ${round(i.overhead.perUnit)} per message (largest residual ${round(i.overhead.maxResidual)} tokens, ${i.overhead.samples} samples)` : 'n/a'}`,
      `- **Unicode reply:** ${i.unicodeText === null ? 'n/a' : JSON.stringify(i.unicodeText)}`,
      `- **Quality:** ${r.quality.replies} replies${r.quality.failures > 0 ? `, ${r.quality.failures} failed` : ''}${r.quality.file ? ` in \`${r.quality.file}\`` : ''}`,
      '',
    );
  }
  return lines.join('\n');
}

export function renderQuality(
  date: string,
  model: string,
  replies: readonly { prompt: string; text: string | null; outputTokens: number | null; error: string | null }[],
): string {
  const lines = [
    `# Reply quality: \`${model}\` (${date})`,
    '',
    'Instructions sent: the planned app prompt (concise, under 120 words). Temperature 1, top_p 1. Judge whether these replies are good enough for the site.',
    '',
  ];
  replies.forEach((r, i) => {
    lines.push(`## ${i + 1}. ${r.prompt}`, '');
    if (r.error) lines.push(`**Failed:** ${r.error}`, '');
    else lines.push(r.text ?? '', '', `_${r.outputTokens ?? '?'} output tokens_`, '');
  });
  return lines.join('\n');
}
