// Builds the token rain's pool (src/content/rain-tokens.json): thousands of real tokens of the tokenizer
// this app uses (o200k_base), so everything that falls on the landing page is a real token.
//
// Words come from tokenizing this project's own writing (the plan, the ADRs, the copy, the sample
// replies), which keeps the vocabulary neutral: a random sample of the whole vocabulary would include
// offensive tokens. Numbers are every one-, two-, and three-digit string, each a single token.
//
//   npm run rain

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { decode, encode } from 'gpt-tokenizer/encoding/o200k_base';

const NO_SPECIAL = { disallowedSpecial: new Set<string>() };
/** Whole-word tokens: a leading space and letters. Tokens without the space are mostly word fragments. */
const WORD = /^ [A-Za-z]{3,12}$/;
/** How many word tokens to keep (numbers are added on top). */
const MAX_WORDS = 3_500;

const docs = [
  'docs/PLAN.md',
  'CLAUDE.md',
  'content/claims.md',
  ...readdirSync('docs/decisions').map((f) => join('docs/decisions', f)),
  ...readdirSync('src/content')
    .filter((f) => f.endsWith('.ts') && !f.includes('.test.'))
    .map((f) => join('src/content', f)),
];
const sample = JSON.parse(readFileSync('fixtures/sample/conversation.json', 'utf8')) as {
  conversation: { turns: { user: { content: string }; assistant: { content: string } | null }[] };
};
const texts = [
  ...docs.map((f) => readFileSync(f, 'utf8')),
  ...sample.conversation.turns.flatMap((t) => [t.user.content, t.assistant?.content ?? '']),
];

const words = new Set<string>();
for (const text of texts) {
  for (const id of encode(text, NO_SPECIAL)) {
    const token = decode([id]);
    if (WORD.test(token)) words.add(token);
  }
}

// A stable spread: sort, then keep an evenly spaced subset if there are more than needed.
const sorted = [...words].sort((a, b) => a.localeCompare(b));
const step = Math.max(1, sorted.length / MAX_WORDS);
const kept = sorted.length <= MAX_WORDS ? sorted : Array.from({ length: MAX_WORDS }, (_, i) => sorted[Math.floor(i * step)] ?? '');
const numbers = Array.from({ length: 1000 }, (_, n) => String(n)).filter((s) => encode(s, NO_SPECIAL).length === 1);
const tokens = [...kept, ...numbers];

writeFileSync(
  'src/content/rain-tokens.json',
  `${JSON.stringify({ tokenizer: 'o200k_base', note: 'Real tokens: whole-word tokens (each with its leading space) found by tokenizing this project’s own writing, plus every number from 0 to 999. Generated by scripts/build-rain-tokens.mts.', tokens })}\n`,
);
console.log(`Wrote src/content/rain-tokens.json: ${kept.length} words and ${numbers.length} numbers (from ${words.size} word tokens found).`);
